server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: iwms-backend
  
  # 数据库配置
  datasource:
    url: jdbc:h2:file:./data/iwms
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  # 安全配置
  security:
    user:
      name: admin
      password: admin123

# 文件存储配置
iwms:
  file:
    upload-dir: ./uploads
    temp-dir: ./temp
    max-file-size: 100MB
    allowed-extensions: jpg,jpeg,png,gif,bmp,tiff,xlsx,xls,csv,txt
  
  # 任务配置
  task:
    max-concurrent: 4
    timeout: 300000 # 5分钟
    
  # 压缩配置
  compression:
    quality: 0.8
    max-width: 1920
    max-height: 1080

# 日志配置
logging:
  level:
    com.iwms: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
