server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: iwms-backend
  
  # 数据库配置
  datasource:
    url: jdbc:h2:file:./data/iwms
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # 安全配置
  security:
    user:
      name: admin
      password: admin123

# 应用配置
iwms:
  app:
    name: IWMS智能文件管理系统
    version: 1.0.0

# 日志配置
logging:
  level:
    com.iwms: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
